Fixed an exception when getting Content Models
Colorado was getting this on occasion:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/stomp/connect.py", line 544, in __receiver_loop
    self.__notify(frame_type, headers, body)
  File "/usr/local/lib/python2.7/dist-packages/stomp/connect.py", line 513, in __notify
    notify_func(headers, body)
  File "/opt/islandora_microservices/islandora_listener.py", line 181, in on_message
    content_models = self._get_fedora_content_models(obj)
  File "/opt/islandora_microservices/islandora_listener.py", line 142, in _get_fedora_content_models
    content_models = [elem['value'].split('/')[1] for elem in ds[NS.fedoramodel.hasModel]]
IndexError: list index out of range

Fixed the listener to catch this error and keep going. Need to eventually figure out where the
unexpected content models are coming from.